// src/config/aiConfig.ts
// 責務: AI（GOAP・戦闘・感情・交配・夜盗）に関するチューニング定数を一元管理する。

export const PERCEPTION = {
  SIGHT_RADIUS: 380,
  CITY_INTERACT_RADIUS: 140,
  ATTACK_RANGE: 60,
  MELEE_RANGE: 70,
  BOW_RANGE: 240,
} as const;

export const COMBAT = {
  BASE_DAMAGE: 8,
  STRENGTH_SCALE: 0.5,
  SKILL_SCALE: 0.4,
  MAGIC_COST: 8,
  DEFENSE_SCALE: 0.3,
  CRIT_CHANCE: 0.12,
  CRIT_MULT: 1.8,
  ATTACK_COOLDOWN: 1.1,
  HEALTH_LOSS_ON_HIT: 1.5,
} as const;

export const RECOVERY = {
  CITY_HP_PER_SEC: 14,
  CITY_MP_PER_SEC: 10,
  CITY_HEALTH_PER_SEC: 6,
  FIELD_HP_PER_SEC: 1.2,
  FIELD_MP_PER_SEC: 0.8,
  FOOD_PER_DAY: 1,
  STARVE_HEALTH_LOSS: 4,
} as const;

export const RELATION = {
  MIN: -100,
  MAX: 100,
  FRIEND_THRESHOLD: 40,
  HATE_THRESHOLD: -40,
  RIVAL_THRESHOLD: 25,
  LOVE_THRESHOLD: 70,
  COMBAT_HELP_GAIN: 6,
  KILL_RELATED_HATE: 60,
  CHAT_FRIEND_GAIN: 4,
  RIVALRY_GAIN: 5,
  DECAY_PER_DAY: 0.5,
} as const;

export const BANDIT = {
  GOLD_THRESHOLD: 5,
  TURN_BANDIT_CHANCE_PER_DAY: 0.04,
  FORT_BUILD_RADIUS: 600,
  ROB_AMOUNT_RATIO: 0.5,
  RECRUIT_STRENGTH_RATIO: 0.7,
  FORT_MAX: 12,
} as const;

export const BREEDING = {
  COOLDOWN_DAYS: 120,
  MIN_HEALTH: 70,
  CHANCE_PER_ENCOUNTER: 0.25,
  CHILD_MATURE_YEARS: 10,
} as const;

export const CHAT = {
  ENCOUNTER_CHAT_CHANCE: 0.015,
  COMBAT_SHOUT_CHANCE: 0.04,
} as const;

export const GOAP = {
  REPLAN_INTERVAL_SEC: 1.4,
  MAX_PLAN_DEPTH: 6,
} as const;